/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.bus_LoaiSanPham;
import DTO.dto_LoaiSanPham;
import DTO.dto_ThuongHieu;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUNG
 */
public class LoaiSanPham extends javax.swing.JFrame {

    private bus_LoaiSanPham loaiSanPhamBUS = new bus_LoaiSanPham();
    private DefaultTableModel tableModelLoaiSanPham;
    /**
     * Creates new form LoaiSanPham
     */
    public LoaiSanPham() {
        initComponents();
        tableModelLoaiSanPham=new DefaultTableModel(new Object[]{"Mã Loại", "Tên Loại"}, 0);
        
        init_tbLoaiSanPham();
    }
    private void init_tbLoaiSanPham() {
        List<dto_LoaiSanPham> DSLoaiSanPham = loaiSanPhamBUS.getAll();

        // Xóa dữ liệu cũ trên bảng
        tableModelLoaiSanPham.setRowCount(0);

        // Thêm dữ liệu mới vào bảng
        for (dto_LoaiSanPham loaisanpham : DSLoaiSanPham) {
            tableModelLoaiSanPham.addRow(new Object[]{loaisanpham.getMaLoaiSanPham(), loaisanpham.getTenLoaiSanPham()});
        }
        
        tbl_LoaiSanPham.setModel(tableModelLoaiSanPham);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_LoaiSanPham = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_TenLoai = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Dong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_MaLoai = new javax.swing.JTextField();
        btn_Sua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOẠI SẢN PHẨM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        tbl_LoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Thương Hiệu", "Tên Thương Hiệu"
            }
        ));
        tbl_LoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LoaiSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_LoaiSanPham);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 338, 238));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên Loại");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 122, 37));
        jPanel1.add(txt_TenLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 210, 37));

        btn_Them.setBackground(new java.awt.Color(0, 153, 0));
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, 35));

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 0));
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 70, 35));

        btn_Dong.setBackground(new java.awt.Color(102, 255, 102));
        btn_Dong.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dong.setText("Đóng");
        btn_Dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DongMouseClicked(evt);
            }
        });
        btn_Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DongActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 80, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã Loại");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 122, 37));
        jPanel1.add(txt_MaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, 37));

        btn_Sua.setBackground(new java.awt.Color(51, 0, 204));
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SuaMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 80, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
            
    }//GEN-LAST:event_formWindowClosing

    private void btn_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseClicked
        // TODO add your handling code here:
        String maLoai = txt_MaLoai.getText();
        String tenLoai = txt_TenLoai.getText();
        
        
        
        if(maLoai.isEmpty() || tenLoai.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"Thêm thất bại! Các trường dữ liệu không được bỏ trống!");
            return;
        }else if(loaiSanPhamBUS.isDuplicateMaLoai(maLoai)){
            JOptionPane.showMessageDialog(rootPane,"Trùng mã loại");
            return;
        }else{
        dto_LoaiSanPham L = new dto_LoaiSanPham(maLoai,tenLoai);
        loaiSanPhamBUS.add(L);
        JOptionPane.showMessageDialog(rootPane,"Thêm thành công");
        txt_MaLoai.setText("");
        txt_TenLoai.setText("");
        }
        
        init_tbLoaiSanPham();

    }//GEN-LAST:event_btn_ThemMouseClicked

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        // TODO add your handling code here:
          int selectedIndexRowRemove = tbl_LoaiSanPham.getSelectedRow();
        if(selectedIndexRowRemove == -1) {
            JOptionPane.showMessageDialog(rootPane,"Bạn chưa chọn Loại Sản Phẩm cần xóa!");
        }
        else {
            // Lấy giá trị của ô tại hàng và cột đã xác định
            String maLoai = tbl_LoaiSanPham.getValueAt(selectedIndexRowRemove, 0).toString();
            if(!maLoai.isEmpty()) {
                loaiSanPhamBUS.delete(maLoai);
                JOptionPane.showMessageDialog(rootPane,"Xóa Loại Sản Phẩm  thành công!");
            }
            init_tbLoaiSanPham();
        }
    }//GEN-LAST:event_btn_XoaMouseClicked

    private void btn_DongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DongMouseClicked
        // TODO add your handling code here:
          String maLoai = txt_MaLoai.getText();
        String tenLoai = txt_TenLoai.getText();

        dto_LoaiSanPham L = new dto_LoaiSanPham(maLoai, tenLoai);
        
        
        if(maLoai.isEmpty() || tenLoai.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"Sửa thất bại! Các trường dữ liệu không được bỏ trống!");
            return;
        }
        
        loaiSanPhamBUS.update(L);
        JOptionPane.showMessageDialog(rootPane,"Sửa thành công");
   
        init_tbLoaiSanPham();
    }//GEN-LAST:event_btn_DongMouseClicked

    private void btn_SuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SuaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SuaMouseClicked

    private void btn_DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_DongActionPerformed

    private void tbl_LoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LoaiSanPhamMouseClicked
        // TODO add your handling code here:
          int selectedRow=tbl_LoaiSanPham.getSelectedRow();
        txt_MaLoai.setText(tbl_LoaiSanPham.getValueAt(selectedRow,0).toString());
         txt_TenLoai.setText(tbl_LoaiSanPham.getValueAt(selectedRow,1).toString());
    }//GEN-LAST:event_tbl_LoaiSanPhamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaiSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Dong;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_LoaiSanPham;
    private javax.swing.JTextField txt_MaLoai;
    private javax.swing.JTextField txt_TenLoai;
    // End of variables declaration//GEN-END:variables
}
