/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HUNG
 */
public class Main extends javax.swing.JFrame {

 

    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundPanel1 = new jpanel.RoundPanel();
        btn_trangchu = new jpanel.RoundPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_nhacungcap = new jpanel.RoundPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_phieunhap = new jpanel.RoundPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_phieuxuat = new jpanel.RoundPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_tonkho = new jpanel.RoundPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_khachhang = new jpanel.RoundPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_taikhoan = new jpanel.RoundPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_thongke = new jpanel.RoundPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_dangxuat = new jpanel.RoundPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        roundPanel2 = new jpanel.RoundPanel();
        imageAvatar1 = new jpanel.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanel_trangchu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpanel_nhacungcap = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpanel_phieunhap = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpanel_phieuxuat = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpanel_tonkho = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpanel_khachhang = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jpanel_taikhoan = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jpanel_thongke = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        roundPanel1.setBackground(new java.awt.Color(51, 51, 51));
        roundPanel1.setRoundBottomLeft(10);
        roundPanel1.setRoundBottomRight(10);
        roundPanel1.setRoundTopLeft(10);
        roundPanel1.setRoundTopRight(10);

        btn_trangchu.setBackground(new java.awt.Color(51, 51, 51));
        btn_trangchu.setRoundBottomLeft(20);
        btn_trangchu.setRoundBottomRight(20);
        btn_trangchu.setRoundTopLeft(20);
        btn_trangchu.setRoundTopRight(20);
        btn_trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_trangchuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_trangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_trangchuMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Trang chủ");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_trangchuLayout = new javax.swing.GroupLayout(btn_trangchu);
        btn_trangchu.setLayout(btn_trangchuLayout);
        btn_trangchuLayout.setHorizontalGroup(
            btn_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_trangchuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_trangchuLayout.setVerticalGroup(
            btn_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_trangchuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_nhacungcap.setBackground(new java.awt.Color(51, 51, 51));
        btn_nhacungcap.setRoundBottomLeft(20);
        btn_nhacungcap.setRoundBottomRight(20);
        btn_nhacungcap.setRoundTopLeft(20);
        btn_nhacungcap.setRoundTopRight(20);
        btn_nhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nhacungcapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nhacungcapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nhacungcapMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nhà cung cấp");

        javax.swing.GroupLayout btn_nhacungcapLayout = new javax.swing.GroupLayout(btn_nhacungcap);
        btn_nhacungcap.setLayout(btn_nhacungcapLayout);
        btn_nhacungcapLayout.setHorizontalGroup(
            btn_nhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_nhacungcapLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_nhacungcapLayout.setVerticalGroup(
            btn_nhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_nhacungcapLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btn_nhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btn_phieunhap.setBackground(new java.awt.Color(51, 51, 51));
        btn_phieunhap.setRoundBottomLeft(20);
        btn_phieunhap.setRoundBottomRight(20);
        btn_phieunhap.setRoundTopLeft(20);
        btn_phieunhap.setRoundTopRight(20);
        btn_phieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_phieunhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_phieunhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_phieunhapMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phiếu nhập");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_phieunhapLayout = new javax.swing.GroupLayout(btn_phieunhap);
        btn_phieunhap.setLayout(btn_phieunhapLayout);
        btn_phieunhapLayout.setHorizontalGroup(
            btn_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_phieunhapLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_phieunhapLayout.setVerticalGroup(
            btn_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_phieunhapLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_phieuxuat.setBackground(new java.awt.Color(51, 51, 51));
        btn_phieuxuat.setRoundBottomLeft(20);
        btn_phieuxuat.setRoundBottomRight(20);
        btn_phieuxuat.setRoundTopLeft(20);
        btn_phieuxuat.setRoundTopRight(20);
        btn_phieuxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_phieuxuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_phieuxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_phieuxuatMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phiếu xuất");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_phieuxuatLayout = new javax.swing.GroupLayout(btn_phieuxuat);
        btn_phieuxuat.setLayout(btn_phieuxuatLayout);
        btn_phieuxuatLayout.setHorizontalGroup(
            btn_phieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_phieuxuatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_phieuxuatLayout.setVerticalGroup(
            btn_phieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_phieuxuatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_phieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel10))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_tonkho.setBackground(new java.awt.Color(51, 51, 51));
        btn_tonkho.setRoundBottomLeft(20);
        btn_tonkho.setRoundBottomRight(20);
        btn_tonkho.setRoundTopLeft(20);
        btn_tonkho.setRoundTopRight(20);
        btn_tonkho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tonkhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tonkhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tonkhoMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tồn kho");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_tonkhoLayout = new javax.swing.GroupLayout(btn_tonkho);
        btn_tonkho.setLayout(btn_tonkhoLayout);
        btn_tonkhoLayout.setHorizontalGroup(
            btn_tonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tonkhoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_tonkhoLayout.setVerticalGroup(
            btn_tonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tonkhoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_tonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel12))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_khachhang.setBackground(new java.awt.Color(51, 51, 51));
        btn_khachhang.setRoundBottomLeft(20);
        btn_khachhang.setRoundBottomRight(20);
        btn_khachhang.setRoundTopLeft(20);
        btn_khachhang.setRoundTopRight(20);
        btn_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_khachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_khachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_khachhangMouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Khách hàng");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_khachhangLayout = new javax.swing.GroupLayout(btn_khachhang);
        btn_khachhang.setLayout(btn_khachhangLayout);
        btn_khachhangLayout.setHorizontalGroup(
            btn_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_khachhangLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_khachhangLayout.setVerticalGroup(
            btn_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_khachhangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel13))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_taikhoan.setBackground(new java.awt.Color(51, 51, 51));
        btn_taikhoan.setRoundBottomLeft(20);
        btn_taikhoan.setRoundBottomRight(20);
        btn_taikhoan.setRoundTopLeft(20);
        btn_taikhoan.setRoundTopRight(20);
        btn_taikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_taikhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_taikhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_taikhoanMouseExited(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tài khoản");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_taikhoanLayout = new javax.swing.GroupLayout(btn_taikhoan);
        btn_taikhoan.setLayout(btn_taikhoanLayout);
        btn_taikhoanLayout.setHorizontalGroup(
            btn_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_taikhoanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_taikhoanLayout.setVerticalGroup(
            btn_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_taikhoanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_thongke.setBackground(new java.awt.Color(51, 51, 51));
        btn_thongke.setRoundBottomLeft(20);
        btn_thongke.setRoundBottomRight(20);
        btn_thongke.setRoundTopLeft(20);
        btn_thongke.setRoundTopRight(20);
        btn_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseExited(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Thống kê");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_thongkeLayout = new javax.swing.GroupLayout(btn_thongke);
        btn_thongke.setLayout(btn_thongkeLayout);
        btn_thongkeLayout.setHorizontalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_thongkeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_thongkeLayout.setVerticalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_thongkeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_dangxuat.setBackground(new java.awt.Color(51, 51, 51));
        btn_dangxuat.setRoundBottomLeft(20);
        btn_dangxuat.setRoundBottomRight(20);
        btn_dangxuat.setRoundTopLeft(20);
        btn_dangxuat.setRoundTopRight(20);
        btn_dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dangxuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dangxuatMouseExited(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Đăng xuất");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_home.png"))); // NOI18N

        javax.swing.GroupLayout btn_dangxuatLayout = new javax.swing.GroupLayout(btn_dangxuat);
        btn_dangxuat.setLayout(btn_dangxuatLayout);
        btn_dangxuatLayout.setHorizontalGroup(
            btn_dangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dangxuatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        btn_dangxuatLayout.setVerticalGroup(
            btn_dangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dangxuatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(btn_dangxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nhacungcap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phieunhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phieuxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tonkho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_khachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_nhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_phieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_phieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        roundPanel2.setBackground(new java.awt.Color(51, 51, 51));
        roundPanel2.setRoundBottomLeft(10);
        roundPanel2.setRoundBottomRight(10);
        roundPanel2.setRoundTopLeft(10);
        roundPanel2.setRoundTopRight(10);

        imageAvatar1.setForeground(new java.awt.Color(102, 204, 255));
        imageAvatar1.setBorderSize(3);
        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image_example (1).jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 750));

        jTabbedPane1.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Trang chủ");

        javax.swing.GroupLayout jpanel_trangchuLayout = new javax.swing.GroupLayout(jpanel_trangchu);
        jpanel_trangchu.setLayout(jpanel_trangchuLayout);
        jpanel_trangchuLayout.setHorizontalGroup(
            jpanel_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_trangchuLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jpanel_trangchuLayout.setVerticalGroup(
            jpanel_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_trangchuLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel4)
                .addContainerGap(528, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jpanel_trangchu);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Nhà cung cấp");

        javax.swing.GroupLayout jpanel_nhacungcapLayout = new javax.swing.GroupLayout(jpanel_nhacungcap);
        jpanel_nhacungcap.setLayout(jpanel_nhacungcapLayout);
        jpanel_nhacungcapLayout.setHorizontalGroup(
            jpanel_nhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_nhacungcapLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jpanel_nhacungcapLayout.setVerticalGroup(
            jpanel_nhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_nhacungcapLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jpanel_nhacungcap);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Phieu nhap");

        javax.swing.GroupLayout jpanel_phieunhapLayout = new javax.swing.GroupLayout(jpanel_phieunhap);
        jpanel_phieunhap.setLayout(jpanel_phieunhapLayout);
        jpanel_phieunhapLayout.setHorizontalGroup(
            jpanel_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_phieunhapLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jpanel_phieunhapLayout.setVerticalGroup(
            jpanel_phieunhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_phieunhapLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jTabbedPane1.addTab("tab3", jpanel_phieunhap);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("phieuxuat");

        javax.swing.GroupLayout jpanel_phieuxuatLayout = new javax.swing.GroupLayout(jpanel_phieuxuat);
        jpanel_phieuxuat.setLayout(jpanel_phieuxuatLayout);
        jpanel_phieuxuatLayout.setHorizontalGroup(
            jpanel_phieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_phieuxuatLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jpanel_phieuxuatLayout.setVerticalGroup(
            jpanel_phieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_phieuxuatLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jTabbedPane1.addTab("tab4", jpanel_phieuxuat);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Ton kho");

        javax.swing.GroupLayout jpanel_tonkhoLayout = new javax.swing.GroupLayout(jpanel_tonkho);
        jpanel_tonkho.setLayout(jpanel_tonkhoLayout);
        jpanel_tonkhoLayout.setHorizontalGroup(
            jpanel_tonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_tonkhoLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jpanel_tonkhoLayout.setVerticalGroup(
            jpanel_tonkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_tonkhoLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jTabbedPane1.addTab("tab5", jpanel_tonkho);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel26.setText("Ton kho");

        javax.swing.GroupLayout jpanel_khachhangLayout = new javax.swing.GroupLayout(jpanel_khachhang);
        jpanel_khachhang.setLayout(jpanel_khachhangLayout);
        jpanel_khachhangLayout.setHorizontalGroup(
            jpanel_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_khachhangLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jpanel_khachhangLayout.setVerticalGroup(
            jpanel_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_khachhangLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jTabbedPane1.addTab("tab6", jpanel_khachhang);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setText("Tai khoan");

        javax.swing.GroupLayout jpanel_taikhoanLayout = new javax.swing.GroupLayout(jpanel_taikhoan);
        jpanel_taikhoan.setLayout(jpanel_taikhoanLayout);
        jpanel_taikhoanLayout.setHorizontalGroup(
            jpanel_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_taikhoanLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jpanel_taikhoanLayout.setVerticalGroup(
            jpanel_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_taikhoanLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jTabbedPane1.addTab("tab7", jpanel_taikhoan);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel28.setText("Thong ke");

        javax.swing.GroupLayout jpanel_thongkeLayout = new javax.swing.GroupLayout(jpanel_thongke);
        jpanel_thongke.setLayout(jpanel_thongkeLayout);
        jpanel_thongkeLayout.setHorizontalGroup(
            jpanel_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_thongkeLayout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        jpanel_thongkeLayout.setVerticalGroup(
            jpanel_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_thongkeLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );

        jTabbedPane1.addTab("tab8", jpanel_thongke);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -40, 1100, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    boolean click_item_menu=true;
    private void btn_trangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trangchuMouseEntered
        // TODO add your handling code here:
          btn_trangchu.setBackground(new Color(52, 125, 252));
          click_item_menu=true;
    }//GEN-LAST:event_btn_trangchuMouseEntered

    private void btn_trangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trangchuMouseExited
        // TODO add your handling code here:
         System.out.println(click_item_menu);
        if(click_item_menu){
             btn_trangchu.setBackground(new Color(51, 51, 51));
        }
         
    }//GEN-LAST:event_btn_trangchuMouseExited

    private void btn_nhacungcapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhacungcapMouseEntered
        // TODO add your handling code here:
         btn_nhacungcap.setBackground(new Color(52, 125, 252));
            click_item_menu=true;
    }//GEN-LAST:event_btn_nhacungcapMouseEntered

    private void btn_nhacungcapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhacungcapMouseExited
        // TODO add your handling code here:
         System.out.println(click_item_menu);
          if(click_item_menu){
             btn_nhacungcap.setBackground(new Color(51, 51, 51));
        }
          System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_nhacungcapMouseExited

    private void btn_trangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_trangchuMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){
            btn_trangchu.setBackground(new Color(52, 125, 252));
             btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
             btn_thongke.setBackground(new Color(51, 51, 51));
             
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_trangchuMouseClicked

    private void btn_nhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nhacungcapMouseClicked
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
        click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){
             btn_nhacungcap.setBackground(new Color(52, 125, 252));
             btn_trangchu.setBackground(new Color(51, 51, 51));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
             btn_thongke.setBackground(new Color(51, 51, 51));
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_nhacungcapMouseClicked

    private void btn_phieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_phieunhapMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
         click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){
             btn_phieunhap.setBackground(new Color(52, 125, 252));
             btn_trangchu.setBackground(new Color(51, 51, 51));
              btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
             btn_thongke.setBackground(new Color(51, 51, 51));
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_phieunhapMouseClicked

    private void btn_phieunhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_phieunhapMouseEntered
        // TODO add your handling code here:
        btn_phieunhap.setBackground(new Color(52, 125, 252));
        click_item_menu=true;
    }//GEN-LAST:event_btn_phieunhapMouseEntered

    private void btn_phieunhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_phieunhapMouseExited
        // TODO add your handling code here:
             // TODO add your handling code here:
         System.out.println(click_item_menu);
          if(click_item_menu){
             btn_phieunhap.setBackground(new Color(51, 51, 51));
        }
          System.out.println(click_item_menu);
       
    }//GEN-LAST:event_btn_phieunhapMouseExited

    private void btn_phieuxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_phieuxuatMouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(3); 
        click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){   
              btn_phieuxuat.setBackground(new Color(52, 125, 252));
             btn_trangchu.setBackground(new Color(51, 51, 51));
              btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
             btn_thongke.setBackground(new Color(51, 51, 51));
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_phieuxuatMouseClicked

    private void btn_tonkhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tonkhoMouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(4); 
        click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){
            btn_tonkho.setBackground(new Color(52, 125, 252));
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
             btn_trangchu.setBackground(new Color(51, 51, 51));
              btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
             btn_thongke.setBackground(new Color(51, 51, 51));
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_tonkhoMouseClicked

    private void btn_phieuxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_phieuxuatMouseEntered
        // TODO add your handling code here:
          btn_phieuxuat.setBackground(new Color(52, 125, 252));
          click_item_menu=true;
    }//GEN-LAST:event_btn_phieuxuatMouseEntered

    private void btn_tonkhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tonkhoMouseEntered
        // TODO add your handling code here:
          btn_tonkho.setBackground(new Color(52, 125, 252));
          click_item_menu=true;
    }//GEN-LAST:event_btn_tonkhoMouseEntered

    private void btn_phieuxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_phieuxuatMouseExited
        // TODO add your handling code here:
         System.out.println(click_item_menu);
          if(click_item_menu){
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
        }
          System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_phieuxuatMouseExited

    private void btn_tonkhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tonkhoMouseExited
        // TODO add your handling code here:
        System.out.println(click_item_menu);
          if(click_item_menu){
             btn_tonkho.setBackground(new Color(51, 51, 51));
        }
        System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_tonkhoMouseExited

    private void btn_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_khachhangMouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(5);
          
              click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){
             btn_khachhang.setBackground(new Color(52, 125, 252));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_trangchu.setBackground(new Color(51, 51, 51));
             btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
             btn_thongke.setBackground(new Color(51, 51, 51));
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_khachhangMouseClicked

    private void btn_khachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_khachhangMouseEntered
        // TODO add your handling code here:
          btn_khachhang.setBackground(new Color(52, 125, 252));
          click_item_menu=true;
    }//GEN-LAST:event_btn_khachhangMouseEntered

    private void btn_khachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_khachhangMouseExited
        // TODO add your handling code here:
          System.out.println(click_item_menu);
          if(click_item_menu){
             btn_khachhang.setBackground(new Color(51, 51, 51));
        }
        System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_khachhangMouseExited

    private void btn_taikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_taikhoanMouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(6);
            click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){
             btn_taikhoan.setBackground(new Color(52, 125, 252));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_trangchu.setBackground(new Color(51, 51, 51));
             btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
            
             btn_thongke.setBackground(new Color(51, 51, 51));
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_taikhoanMouseClicked

    private void btn_taikhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_taikhoanMouseEntered
        // TODO add your handling code here:
          btn_taikhoan.setBackground(new Color(52, 125, 252));
          click_item_menu=true;
    }//GEN-LAST:event_btn_taikhoanMouseEntered

    private void btn_taikhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_taikhoanMouseExited
        // TODO add your handling code here:
        System.out.println(click_item_menu);
        if(click_item_menu){
            btn_taikhoan.setBackground(new Color(51, 51, 51));
        }
        System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_taikhoanMouseExited

    private void btn_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(7);
            click_item_menu=true;
         System.out.println(click_item_menu);
        if(click_item_menu){
              btn_thongke.setBackground(new Color(52, 125, 252));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_trangchu.setBackground(new Color(51, 51, 51));
             btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieuxuat.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
           
        }
        click_item_menu=false;
         System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_thongkeMouseClicked

    private void btn_thongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseEntered
        // TODO add your handling code here:
          btn_thongke.setBackground(new Color(52, 125, 252));
          click_item_menu=true;
    }//GEN-LAST:event_btn_thongkeMouseEntered

    private void btn_thongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseExited
        // TODO add your handling code here:
        System.out.println(click_item_menu);
        if(click_item_menu){
             btn_thongke.setBackground(new Color(51, 51, 51));
        }
        System.out.println(click_item_menu);
    }//GEN-LAST:event_btn_thongkeMouseExited

    private void btn_dangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangxuatMouseClicked
        // TODO add your handling code here:
          jTabbedPane1.setSelectedIndex(8);
          
             btn_phieuxuat.setBackground(new Color(52, 125, 252));
             btn_trangchu.setBackground(new Color(51, 51, 51));
              btn_nhacungcap.setBackground(new Color(51, 51, 51));
             btn_phieunhap.setBackground(new Color(51, 51, 51));
             btn_tonkho.setBackground(new Color(51, 51, 51));
             btn_khachhang.setBackground(new Color(51, 51, 51));
             btn_taikhoan.setBackground(new Color(51, 51, 51));
             btn_thongke.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_btn_dangxuatMouseClicked

    private void btn_dangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangxuatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangxuatMouseEntered

    private void btn_dangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangxuatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangxuatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jpanel.RoundPanel btn_dangxuat;
    private jpanel.RoundPanel btn_khachhang;
    private jpanel.RoundPanel btn_nhacungcap;
    private jpanel.RoundPanel btn_phieunhap;
    private jpanel.RoundPanel btn_phieuxuat;
    private jpanel.RoundPanel btn_taikhoan;
    private jpanel.RoundPanel btn_thongke;
    private jpanel.RoundPanel btn_tonkho;
    private jpanel.RoundPanel btn_trangchu;
    private jpanel.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpanel_khachhang;
    private javax.swing.JPanel jpanel_nhacungcap;
    private javax.swing.JPanel jpanel_phieunhap;
    private javax.swing.JPanel jpanel_phieuxuat;
    private javax.swing.JPanel jpanel_taikhoan;
    private javax.swing.JPanel jpanel_thongke;
    private javax.swing.JPanel jpanel_tonkho;
    private javax.swing.JPanel jpanel_trangchu;
    private jpanel.RoundPanel roundPanel1;
    private jpanel.RoundPanel roundPanel2;
    // End of variables declaration//GEN-END:variables
}
