/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.bus_MauSac;
import DTO.dto_MauSac;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUNG
 */
public class MauSac extends javax.swing.JFrame {

    private bus_MauSac mauSacBUS = new bus_MauSac();
    private DefaultTableModel tableModelmauSac;

    /**
     * Creates new form ThuongHieu
     */
    public MauSac() {
        initComponents();
        tableModelmauSac=new DefaultTableModel(new Object[]{"Mã Màu Sắc", "Tên Màu Sắc"}, 0);
        
        init_tbMauSac();
    }
    private void init_tbMauSac() {
        List<dto_MauSac> DSMauSac = mauSacBUS.getAll();

        // Xóa dữ liệu cũ trên bảng
        tableModelmauSac.setRowCount(0);

        // Thêm dữ liệu mới vào bảng
        for (dto_MauSac mauSac : DSMauSac) {
            tableModelmauSac.addRow(new Object[]{mauSac.getMaMauSac(),mauSac.getTenMauSac()});
        }
        
        tbl_MauSac.setModel(tableModelmauSac);
           System.out.println(tableModelmauSac);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_MauSac = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_TenMau = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_MaMau = new javax.swing.JTextField();
        btn_Dong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MÀU SẮC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        tbl_MauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Màu", "Tên Màu"
            }
        ));
        tbl_MauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_MauSacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_MauSac);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 338, 238));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên Màu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 122, 37));
        jPanel1.add(txt_TenMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 210, 37));

        btn_Them.setBackground(new java.awt.Color(0, 153, 0));
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 35));

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 0));
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 80, 35));

        btn_Sua.setBackground(new java.awt.Color(51, 0, 204));
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 80, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã Màu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 122, 37));
        jPanel1.add(txt_MaMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 37));

        btn_Dong.setBackground(new java.awt.Color(153, 255, 153));
        btn_Dong.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dong.setText("Đóng");
        btn_Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DongActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 80, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
       String maMau = txt_MaMau.getText();
        String tenMau= txt_TenMau.getText();
        
      
        
        if(maMau.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"Thêm thất bại! Các trường dữ liệu không được bỏ trống!");
            return;
        }else if(mauSacBUS.isDuplicateMaMauSac(maMau)){
            JOptionPane.showMessageDialog(rootPane,"Trùng mã màu");
            return;
        }
        dto_MauSac MS = new dto_MauSac(maMau,tenMau);
        mauSacBUS.add(MS);
        JOptionPane.showMessageDialog(rootPane,"Thêm thành công");
        txt_MaMau.setText("");
        txt_TenMau.setText("");
        init_tbMauSac();

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
         int selectedIndexRowRemove = tbl_MauSac.getSelectedRow();
        if(selectedIndexRowRemove == -1) {
            JOptionPane.showMessageDialog(rootPane,"Bạn chưa chọn Màu Sắc cần xóa!");
        }
        else {
            // Lấy giá trị của ô tại hàng và cột đã xác định
            String maMau = tbl_MauSac.getValueAt(selectedIndexRowRemove, 0).toString();
            if(!maMau.isEmpty()) {
                mauSacBUS.delete(maMau);
                JOptionPane.showMessageDialog(rootPane,"Xóa Màu Sắc thành công!");
            }
            init_tbMauSac();
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String maMau = txt_MaMau.getText();
        String tenMau = txt_TenMau.getText();

        dto_MauSac MS = new dto_MauSac(maMau , tenMau);
        
        
        if(maMau.isEmpty() || tenMau.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,"Sửa thất bại! Các trường dữ liệu không được bỏ trống!");
            return;
        }
        
        mauSacBUS.update(MS);
        JOptionPane.showMessageDialog(rootPane,"Sửa thành công");
   
        init_tbMauSac();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_DongActionPerformed

    private void tbl_MauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_MauSacMouseClicked
        // TODO add your handling code here:
         int selectedRow=tbl_MauSac.getSelectedRow();
        txt_MaMau.setText(tbl_MauSac.getValueAt(selectedRow,0).toString());
         txt_TenMau.setText(tbl_MauSac.getValueAt(selectedRow,1).toString());

    }//GEN-LAST:event_tbl_MauSacMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MauSac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Dong;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_MauSac;
    private javax.swing.JTextField txt_MaMau;
    private javax.swing.JTextField txt_TenMau;
    // End of variables declaration//GEN-END:variables
}
