/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.bus_ThuongHieu;
import DTO.dto_ThuongHieu;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUNG
 */
public class ThuongHieu extends javax.swing.JFrame {

    private bus_ThuongHieu thuongHieuBUS = new bus_ThuongHieu();
    private DefaultTableModel tableModelthuongHieu;

    /**
     * Creates new form ThuongHieu
     */
    public ThuongHieu() {
        initComponents();
        tableModelthuongHieu = new DefaultTableModel(new Object[]{"Mã Thương Hiệu", "Tên Thương Hiệu"}, 0);

        init_tbThuongHieu();
    }

    private void init_tbThuongHieu() {
        List<dto_ThuongHieu> DSThuongHieu = thuongHieuBUS.getAll();

        // Xóa dữ liệu cũ trên bảng
        tableModelthuongHieu.setRowCount(0);

        // Thêm dữ liệu mới vào bảng
        for (dto_ThuongHieu thuongHieu : DSThuongHieu) {
            tableModelthuongHieu.addRow(new Object[]{thuongHieu.getMaThuongHieu(), thuongHieu.getTenThuongHieu()});
        }

        tbl_ThuongHieu.setModel(tableModelthuongHieu);
        System.out.println(tableModelthuongHieu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ThuongHieu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_TenThuongHieu = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_MaThuongHieu = new javax.swing.JTextField();
        btn_Dong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THƯƠNG HIỆU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        tbl_ThuongHieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Thương Hiệu", "Tên Thương Hiệu"
            }
        ));
        tbl_ThuongHieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ThuongHieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ThuongHieu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 338, 238));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên Thương Hiệu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 122, 37));

        txt_TenThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenThuongHieuActionPerformed(evt);
            }
        });
        jPanel1.add(txt_TenThuongHieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 210, 37));

        btn_Them.setBackground(new java.awt.Color(0, 153, 0));
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 35));

        btn_Xoa.setBackground(new java.awt.Color(255, 0, 0));
        btn_Xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 70, 35));

        btn_Sua.setBackground(new java.awt.Color(51, 0, 204));
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 80, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã Thương Hiệu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 122, 37));
        jPanel1.add(txt_MaThuongHieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 37));

        btn_Dong.setBackground(new java.awt.Color(153, 255, 153));
        btn_Dong.setForeground(new java.awt.Color(255, 255, 255));
        btn_Dong.setText("Đóng");
        btn_Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DongActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 80, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
       String maThuongHieu = txt_MaThuongHieu.getText();
        String tenThuongHieu = txt_TenThuongHieu.getText();

       

        if (maThuongHieu.isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại! Các trường dữ liệu không được bỏ trống!");
            return;
        }
        else if(thuongHieuBUS.isDuplicateMaThuongHieu(maThuongHieu)){
            JOptionPane.showMessageDialog(rootPane, "Trùng mã thương hiệu");
            return;
        }else{
        dto_ThuongHieu TH = new dto_ThuongHieu(maThuongHieu, tenThuongHieu);
        thuongHieuBUS.add(TH);
        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        txt_MaThuongHieu.setText("");
        txt_TenThuongHieu.setText("");
        }
        init_tbThuongHieu();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed

        int selectedIndexRowRemove = tbl_ThuongHieu.getSelectedRow();
        if (selectedIndexRowRemove == -1) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn Thương Hiệu cần xóa!");
        } else {
            // Lấy giá trị của ô tại hàng và cột đã xác định
            String maThuongHieu = tbl_ThuongHieu.getValueAt(selectedIndexRowRemove, 0).toString();
            if (!maThuongHieu.isEmpty()) {
                thuongHieuBUS.delete(maThuongHieu);
                JOptionPane.showMessageDialog(rootPane, "Xóa Thương Hiệu thành công!");
            }
            init_tbThuongHieu();
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String maThuongHieu = txt_MaThuongHieu.getText();
        String tenThuongHieu = txt_TenThuongHieu.getText();

        dto_ThuongHieu TH = new dto_ThuongHieu(maThuongHieu, tenThuongHieu);

        if (maThuongHieu.isEmpty() || tenThuongHieu.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Sửa thất bại! Các trường dữ liệu không được bỏ trống!");
            return;
        }

        thuongHieuBUS.update(TH);
        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");

        init_tbThuongHieu();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void txt_TenThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenThuongHieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenThuongHieuActionPerformed

    private void btn_DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_DongActionPerformed

    private void tbl_ThuongHieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ThuongHieuMouseClicked
        // TODO add your handling code here:
         int selectedRow=tbl_ThuongHieu.getSelectedRow();
        txt_MaThuongHieu.setText(tbl_ThuongHieu.getValueAt(selectedRow,0).toString());
         txt_TenThuongHieu.setText(tbl_ThuongHieu.getValueAt(selectedRow,1).toString());

    }//GEN-LAST:event_tbl_ThuongHieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuongHieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThuongHieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Dong;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ThuongHieu;
    private javax.swing.JTextField txt_MaThuongHieu;
    private javax.swing.JTextField txt_TenThuongHieu;
    // End of variables declaration//GEN-END:variables
}
